### ISSUE TITLE
Object IDs

### ISSUE THREAD

**Issue by gjahesh** [ropensci/musemeta#12]
Hi there,

A simple question is that where are object IDs coming from? Usually the on-line collections like the one in MET provides only the accession numbers.

Thanks,
Golnaz

**Comment by sckott** [comment]
hi, thanks for the question. 

As an example, for this request for ID `559490` we get:

```r
met(559490)
#> <Museum metadata> Siphon nozzle
#>   Period: New Kingdom, Ramesside
#>   Dynasty: Dynasty 19 20
#>   Date: ca. 1295 1070 B.C.
#>   Geography: From Egypt, Memphite Region, Lisht North, Cemetery, MMA excavations, 1913 14
#>   Medium: Bronze
#>   Dimensions: l. 5.4 cm (2 1/8 in)
#>   Credit Line: Rogers Fund and Edward S. Harkness Gift, 1922
#>   Accession Number: 22.1.962
```

The ID used is the one in the URL for the object http://metmuseum.org/collection/the-collection-online/search/559490  They don't have accession numbers in the URLs. 

We also have access to MET via the Scrapi service http://scrapi.org/ See functions `scrapi_*()` in this package. Those functions also use the same IDs from the URLs on the MET site for requesting metadata on an object. You can search with scrapi on the accession number e.g, `scrapi_search(query='22.1.962')`, but I don't think that search is just searching on accession numbers, as it does return a lot of results 

Does that help?

**Comment by gjahesh** [comment]
Hi Scott,

Thanks for the reply. I basically wanted to know if there's a way to get object IDs , without having to search for the objects.Lets say when you search the online collection for a particular country (Geographic location) in a specific Department, then you have a long list of objects, and it's kind of hard to go through each ,one by one.

I also tried `scrapi_search` function example but I get the following error:

```
scrapi_search(query='mirror')
```
Error in setNames(unname(unlist(out$`_links`)), names(out$`_links`)) : 
  'names' attribute [4] must be the same length as the vector [3]

Thanks,
Golnaz

**Comment by sckott** [comment]
> I basically wanted to know if there's a way to get object IDs , without having to search for the objects

should be able to do with `scrapi_search()`, see next comment

> I also tried scrapi_search function example but I get the following error:

try reinstalling the package first, i just fixed that error I think

**Comment by gjahesh** [comment]
reinstalled the package, still the same error for `scrapi_search()`

**Comment by sckott** [comment]
woops, i forgot to push up those changes to this repo. try again after reinstalling. I get:

```r
<r> scrapi_search(query='mirror')
$links
 [1] "http://scrapi.org/object/84805"  "http://scrapi.org/object/212130" "http://scrapi.org/object/56198"  "http://scrapi.org/object/373011"
 [5] "http://scrapi.org/object/282526" "http://scrapi.org/object/450168" "http://scrapi.org/object/435086" "http://scrapi.org/object/632196"
 [9] "http://scrapi.org/object/546116" "http://scrapi.org/object/13674"  "http://scrapi.org/object/217981" "http://scrapi.org/object/368284"
[13] "http://scrapi.org/object/406162" "http://scrapi.org/object/376871" "http://scrapi.org/object/355489" "http://scrapi.org/object/59038" 
[17] "http://scrapi.org/object/141484" "http://scrapi.org/object/692593" "http://scrapi.org/object/206692" "http://scrapi.org/object/489296"
[21] "http://scrapi.org/object/69204"  "http://scrapi.org/object/272633" "http://scrapi.org/object/29998"  "http://scrapi.org/object/646437"
[25] "http://scrapi.org/object/121471" "http://scrapi.org/object/191795" "http://scrapi.org/object/325741" "http://scrapi.org/object/554827"
[29] "http://scrapi.org/object/39211"  "http://scrapi.org/object/377431" "http://scrapi.org/object/81320"  "http://scrapi.org/object/352542"
[33] "http://scrapi.org/object/266603" "http://scrapi.org/object/212262" "http://scrapi.org/object/211047" "http://scrapi.org/object/375540"
[37] "http://scrapi.org/object/78617"  "http://scrapi.org/object/361612" "http://scrapi.org/object/13901"  "http://scrapi.org/object/28086" 
[41] "http://scrapi.org/object/335874" "http://scrapi.org/object/704504" "http://scrapi.org/object/632853" "http://scrapi.org/object/307651"
[45] "http://scrapi.org/object/451232" "http://scrapi.org/object/223836" "http://scrapi.org/object/388022" "http://scrapi.org/object/168521"
[49] "http://scrapi.org/object/422981" "http://scrapi.org/object/505504" "http://scrapi.org/object/431484" "http://scrapi.org/object/118894"
[53] "http://scrapi.org/object/42242"  "http://scrapi.org/object/326866" "http://scrapi.org/object/223643" "http://scrapi.org/object/62510" 
[57] "http://scrapi.org/object/174373" "http://scrapi.org/object/399522" "http://scrapi.org/object/199407" "http://scrapi.org/object/55445" 
[61] "http://scrapi.org/object/394874" "http://scrapi.org/object/563759" "http://scrapi.org/object/355691" "http://scrapi.org/object/557131"
[65] "http://scrapi.org/object/450223" "http://scrapi.org/object/347705" "http://scrapi.org/object/420391" "http://scrapi.org/object/197695"
[69] "http://scrapi.org/object/267954" "http://scrapi.org/object/245636" "http://scrapi.org/object/393140" "http://scrapi.org/object/368197"
[73] "http://scrapi.org/object/83918"  "http://scrapi.org/object/31274"  "http://scrapi.org/object/413642" "http://scrapi.org/object/451965"
[77] "http://scrapi.org/object/34947"  "http://scrapi.org/object/660475" "http://scrapi.org/object/471739" "http://scrapi.org/object/549100"
[81] "http://scrapi.org/object/119186" "http://scrapi.org/object/378862" "http://scrapi.org/object/360619" "http://scrapi.org/object/74680" 
[85] "http://scrapi.org/object/221537" "http://scrapi.org/object/107368" "http://scrapi.org/object/283717" "http://scrapi.org/object/686571"
[89] "http://scrapi.org/object/97481"  "http://scrapi.org/object/50158" 

$ids
 [1] "84805"  "212130" "56198"  "373011" "282526" "450168" "435086" "632196" "546116" "13674"  "217981" "368284" "406162" "376871" "355489" "59038" 
[17] "141484" "692593" "206692" "489296" "69204"  "272633" "29998"  "646437" "121471" "191795" "325741" "554827" "39211"  "377431" "81320"  "352542"
[33] "266603" "212262" "211047" "375540" "78617"  "361612" "13901"  "28086"  "335874" "704504" "632853" "307651" "451232" "223836" "388022" "168521"
[49] "422981" "505504" "431484" "118894" "42242"  "326866" "223643" "62510"  "174373" "399522" "199407" "55445"  "394874" "563759" "355691" "557131"
[65] "450223" "347705" "420391" "197695" "267954" "245636" "393140" "368197" "83918"  "31274"  "413642" "451965" "34947"  "660475" "471739" "549100"
[81] "119186" "378862" "360619" "74680"  "221537" "107368" "283717" "686571" "97481"  "50158" 

$paging
$paging$first
[1] "http://scrapi.org/search/mirror?page=1"

$paging$`next`
[1] "http://scrapi.org/search/mirror?page=2"

$paging$last
[1] "http://scrapi.org/search/mirror?page=4669"
```

**Comment by gjahesh** [comment]
Works fine now, thanks for the update.
